; Listing generated by Microsoft (R) Optimizing Compiler Version 18.00.21005.1 

	TITLE	G:\ª„±‡”Ô—‘–¬ È µ¿˝\C13_float\c_float_add\c_float_add.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

PUBLIC	_main
PUBLIC	??_C@_03PPOCCAPH@?$CFf?6?$AA@			; `string'
PUBLIC	__real@4048f5c3
PUBLIC	__real@40600000
PUBLIC	__real@40b66e98
EXTRN	__imp__printf:PROC
EXTRN	__RTC_CheckEsp:PROC
EXTRN	__RTC_InitBase:PROC
EXTRN	__RTC_Shutdown:PROC
EXTRN	__fltused:DWORD
;	COMDAT __real@40b66e98
CONST	SEGMENT
__real@40b66e98 DD 040b66e98r			; 5.701
CONST	ENDS
;	COMDAT __real@40600000
CONST	SEGMENT
__real@40600000 DD 040600000r			; 3.5
CONST	ENDS
;	COMDAT __real@4048f5c3
CONST	SEGMENT
__real@4048f5c3 DD 04048f5c3r			; 3.14
CONST	ENDS
;	COMDAT rtc$TMZ
rtc$TMZ	SEGMENT
__RTC_Shutdown.rtc$TMZ DD FLAT:__RTC_Shutdown
rtc$TMZ	ENDS
;	COMDAT rtc$IMZ
rtc$IMZ	SEGMENT
__RTC_InitBase.rtc$IMZ DD FLAT:__RTC_InitBase
rtc$IMZ	ENDS
;	COMDAT ??_C@_03PPOCCAPH@?$CFf?6?$AA@
CONST	SEGMENT
??_C@_03PPOCCAPH@?$CFf?6?$AA@ DB '%f', 0aH, 00H		; `string'
CONST	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File g:\ª„±‡”Ô—‘–¬ È µ¿˝\c13_float\c_float_add\c_float_add.c
;	COMDAT _main
_TEXT	SEGMENT
_z$ = -48						; size = 8
_u$ = -32						; size = 4
_y$ = -20						; size = 4
_x$ = -8						; size = 4
_argc$ = 8						; size = 4
_argv$ = 12						; size = 4
_main	PROC						; COMDAT

; 4    : {

	push	ebp
	mov	ebp, esp
	sub	esp, 244				; 000000f4H
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-244]
	mov	ecx, 61					; 0000003dH
	mov	eax, -858993460				; ccccccccH
	rep stosd

; 5    : 	float x, y,u;
; 6    : 	double z;
; 7    : 	x = 3.14;

	fld	DWORD PTR __real@4048f5c3
	fstp	DWORD PTR _x$[ebp]

; 8    : 	y = 5.701;

	fld	DWORD PTR __real@40b66e98
	fstp	DWORD PTR _y$[ebp]

; 9    : 	u = 3.5;

	fld	DWORD PTR __real@40600000
	fstp	DWORD PTR _u$[ebp]

; 10   : 	z = x + y+u;

	fld	DWORD PTR _x$[ebp]
	fadd	DWORD PTR _y$[ebp]
	fadd	DWORD PTR _u$[ebp]
	fstp	QWORD PTR _z$[ebp]

; 11   : 	printf("%f\n", z);

	mov	esi, esp
	sub	esp, 8
	fld	QWORD PTR _z$[ebp]
	fstp	QWORD PTR [esp]
	push	OFFSET ??_C@_03PPOCCAPH@?$CFf?6?$AA@
	call	DWORD PTR __imp__printf
	add	esp, 12					; 0000000cH
	cmp	esi, esp
	call	__RTC_CheckEsp

; 12   : 	return 0;

	xor	eax, eax

; 13   : }

	pop	edi
	pop	esi
	pop	ebx
	add	esp, 244				; 000000f4H
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
_main	ENDP
_TEXT	ENDS
END
